In [1]:
import numpy as np
A = np.arange(6).reshape(3,2)
B = np.arange(8).reshape(2,4)
print(A)
print(B)

[[0 1]
 [2 3]
 [4 5]]
[[0 1 2 3]
 [4 5 6 7]]


In [4]:
C = np.dot(A, B)
print(C)

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


In [5]:
print(np.max(C))

47
